### ISSUE TITLE
Use `--message-format=json` for getting the location of the generated files

### ISSUE THREAD

**Issue by konstin** [rustwasm/wasm-pack#333]
## 💡 Feature description

Currently, wasm-pack tries to guess the location of the asset from the Cargo.toml. With  `--message-format=json` we can get the location directly from cargo. 

This should also fix #252.

#### 💻 Basic example

```json
{
  "features": [],
  "filenames": [
    "/home/konsti/pyo3-pack/points/target/debug/libpoints.so"
  ],
  "fresh": true,
  "package_id": "points 0.1.0 (path+file:///home/konsti/pyo3-pack/points)",
  "profile": {
    "debug_assertions": true,
    "debuginfo": 2,
    "opt_level": "0",
    "overflow_checks": true,
    "test": false
  },
  "reason": "compiler-artifact",
  "target": {
    "crate_types": [
      "cdylib"
    ],
    "edition": "2015",
    "kind": [
      "cdylib"
    ],
    "name": "points",
    "src_path": "/home/konsti/pyo3-pack/points/src/lib.rs"
  }
}
```

Implementation in pyo3-pack: https://github.com/PyO3/pyo3-pack/blob/2f0c8a926bf1b607c48589a2393604de322f7f40/src/compile.rs#L221-L232

cargo-metadata has a [pending pull request](https://github.com/oli-obk/cargo_metadata/pull/53) which wraps cargo's messages in a nice api we could use.

**Comment by alexcrichton** [comment]
I think unfortunately we won't be able to switch to doing this in the near future because when Cargo is placed in json message mode it also places the compiler in json message mode. We don't have a great way to rerender an error message as desired by rustc later on which means we wouldn't be able to render rustc's error messages faithfully to the console.

I think, though, that with recent improvements and bug fixes we should be pretty good to go here. Cargo should always produce predictable output for a package so long as we hook up the directories and such correctly. For now we'll have to implement that logic manually, but perhaps in the future we can also add a feature to Cargo to have cargo emit json messages and have rustc still emit normal error messages!
