### ISSUE TITLE
wasm-bindgen download URL is not always valid

### ISSUE THREAD

**Issue by spencerwilson** [rustwasm/wasm-pack#343]
## 🐛 Bug description
When Cargo.toml specifices a range like `wasm-bindgen = "0.2"`, wasm-pack's attempt to fetch a prebuilt binary goes thusly:
```
Sep 23 09:37:48.487 WARN could not download pre-built `wasm-bindgen`: received a bad HTTP status code (404) when requesting https://github.com/rustwasm/wasm-bindgen/releases/download/0.2/wasm-bindgen-0.2-x86_64-apple-darwin.tar.gz. Falling back to `cargo install`.
```

wasm-bindgen, however, does releases of concrete semver versions, e.g., `x.y.z`. If both `0.2`s are substituted with `0.2.22` (for example), it doesn't 404.

#### 🤔 Expected Behavior
I think it'd be nice if wasm-pack, when fetching wasm-bindgen, had the following behavior: If the current project's wasm-bindgen requirement is...

- **specific**, it attempts to fetch a prebuilt binary for that release. (This should be working today.)
- a **range constraint**, it attempts to fetch the latest release that satisfies that constraint.

The latter may not be worth the effort (probably querying the GitHub API), so maybe "it attempts to fetch the first release satisfying that constraint", i.e., appending `".0"`s as necessary until it's of the form `x.y.z`.

#### 👟 Steps to reproduce
Implied above.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 7df088caada068f4e7f93ff37da3284ef082e95c
rustc version: rustc 1.29.0 (aa3ca1994 2018-09-11)

**Comment by spencerwilson** [comment]
Might be moot under https://github.com/rustwasm/wasm-pack/pull/302, where the notion of 'desired version of wasm-bindgen' is always a concrete version.

**Comment by ashleygwilliams** [comment]
hey @spencerwilson ! sorry you ran into this- the reason we've been waiting on release is because we need #302 to land. i'm pretty sure that #302 should fix this- and it will be similar to what you specced out, except instead of grabbing latest, it will grab whatever version of wasm-bindgen you have in Cargo.lock. wasm-bindgen requires that its version match, so snagging latest would sadly not work. thanks for filing a really detailed report- hopefully all of this will happen tomorrow and the new release should fix all your woes :)
