### ISSUE TITLE
unresolved import `wasm_bindgen_macro::wasm_bindgen`

### ISSUE THREAD

**Issue by marcocastignoli** [rustwasm/wasm-pack#374]
## 🐛 Bug description
```
Compiling wasm-bindgen v0.2.22
error[E0432]: unresolved import `wasm_bindgen_macro::wasm_bindgen`
  --> /home/MYNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.22/src/lib.rs:39:13
   |
39 |     pub use wasm_bindgen_macro::wasm_bindgen;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `wasm_bindgen` in the root

error: aborting due to previous error
```

#### 🤔 Expected Behavior
It should compile

#### 👟 Steps to reproduce
I followed the https://github.com/rustwasm/wasm-pack#-quickstart-guide, it breaks at step 
```
wasm-pack init
```

#### 🌍 Your environment
wasm-pack version: 0.4.2
rustc version: 1.29.0-nightly

**Comment by ashleygwilliams** [comment]
hi @marcocastignoli ! i'm pretty sure this is because the latest wasm-bindgen requires rust version 1.30.0. you can install that using `rustup install beta` or `rustup install nightly`.

while you're at it- we released a new version of wasm-pack yesterday- i'd check it out, the user experience is way improved! (and helps catch things like this)

lemme know if you are still having issues!
