### ISSUE TITLE
Unable to build because Rust version is not 1.30.0 or higher

### ISSUE THREAD

**Issue by jose-zama** [rustwasm/wasm-pack#397]
## 🐛 Bug description
Unable to do `wasm-pack build`.
Output:
```
Your version of Rust, '1.29', is not supported. Please install Rust version 1.30.0 or higher.
```

#### 🤔 Expected Behavior
Build the wasm-pack project.
At this moment, the last release of Rust is 1.29. There is no 1.30.0 (as far as i know)

#### 👟 Steps to reproduce
1. Create a project with the template `cargo generate --git https://github.com/rustwasm/wasm-pack-template`
1. Build. `wasm-pack build`

#### 🌍 Your environment
wasm-pack version: 0.5.0
rustc version: 1.29.0 (aa3ca1994 2018-09-11)
os: OS X El Capitan 10.11.6

**Comment by ashleygwilliams** [comment]
hi @jose-zama and thanks for filing! it turns out that that error message is accurate- though certainly not as useful as it should be. Rust 1.30 (and beyond) exists- but currently only on the `beta` and `nightly` channels. to fix your situation, you can run `rustup override set beta` or `rustup override set nightly` and you should be all set. i'm going to close, but please reopen if you continue to have trouble!

**Comment by ashleygwilliams** [comment]
oh and to clarify that `rustup` command will declare that you want to use that channel in the directory, this avoids changing your default rust version, so any other projects you have should be unaffected!

**Comment by jose-zama** [comment]
Thanks. Glad that decided to create the issue. The response was lighting fast!

So yeah. That fixed the problem. I should have thought about the beta/nightly releases.
