### ISSUE TITLE
wasm-pack compiler error - unix module not found 

### ISSUE THREAD

**Issue by glauserr** [rustwasm/wasm-pack#559]
## 🐛 Bug description

```
  error[E0433]: failed to resolve: could not find `unix` in `os`
    --> /home/regl/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-1.0.4/src/lin.rs:41:18
     |
  41 |     use std::os::unix::ffi::OsStringExt;
     |                  ^^^^ could not find `unix` in `os`
  
  error[E0432]: unresolved import `unix`
   --> /home/regl/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-1.0.4/src/lin.rs:6:5
    |
  6 | use unix;
    |     ^^^^ no `unix` in the root
  ```

#### 🤔 Expected Behavior
I built the code with "cargo built" to make sure I can successfully build the project. When I want to build with wasm-pack I get the described error to build the dependency "dirs-1.0.4". Since I can build it with cargo build it must be an error of wasm-pack 

#### 🌍 Your environment
linux: ubuntu 18.04.2 LTS
wasm-pack version: 0.6
rustc version: 1.32.0

**Comment by alexcrichton** [comment]
Thanks for the report! This is a bug/feature report, however, for the `dirs` crate. The crate looks like it's not ready to compile to wasm yet and the crate itself will need to be modified to compile for the `wasm32-unknown-unknown` target. (typically this involves returning errors on I/O or otherwise changing to tweak idioms for wasm)

**Comment by fitzgen** [comment]
This document should help `dirs` folks add support for wasm as well: https://rustwasm.github.io/book/reference/add-wasm-support-to-crate.html

**Comment by CrocdileChan** [comment]
I find the same problem when I build the paritytech/substrate project.  
when it compiles dirs, it shows that:



>  Compiling dirs v1.0.5
   Compiling rand_jitter v0.1.4
   Compiling typenum v1.10.0
   Compiling libc v0.2.60
   Compiling crossbeam-utils v0.6.6
   Compiling owning_ref v0.4.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> /Users/ChenXinRan/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-1.0.5/src/lin.rs:41:18
   |
41 |     use std::os::unix::ffi::OsStringExt;
   |                  ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `unix`
 --> /Users/ChenXinRan/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-1.0.5/src/lin.rs:6:5
  |
6 | use unix;
  |     ^^^^ no `unix` in the root

error[E0599]: no function or associated item named `from_vec` found for type `std::ffi::OsString` in the current scope
  --> /Users/ChenXinRan/.cargo/registry/src/github.com-1ecc6299db9ec823/dirs-1.0.5/src/lin.rs:48:34
   |
48 |     Some(PathBuf::from(OsString::from_vec(out)))
   |                                  ^^^^^^^^ function or associated item not found in `std::ffi::OsString`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use std::sys_common::os_str_bytes::OsStringExt;`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `dirs`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by CrocdileChan** [comment]
macOSX  10.11.2

rustup 1.18.3 (435397f48 2019-05-22)

rustc 1.38.0-nightly (69656fa4c 2019-07-13)

**Comment by Pauan** [comment]
I suspect this isn't actually an issue with building the project, instead I think it's an issue with compiling wasm-bindgen from source.

@glauserr @CrocdileChan Could you check and see if you have a `.cargo/config` file somewhere (maybe in your HOME folder) which contains something like this?

```toml
[build]
target = "wasm32-unknown-unknown"
```
