### ISSUE TITLE
check wasm-bindgen version if target = web is passed

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#627]
we've seen some people get confused by the error message about an incorrect argument when wasm-pack build --target web is run on a project that depends on a wasm-bindgen that didn't support that target. we should give an error message that tells folks to update their wasm-bindgen dep in their Cargo.toml.

**Comment by gameldar** [comment]
After looking through the wasm-bindgen changelog to find the appropriate minimum version of wasm-bindgen to depend upon I was going to create a new issue because --web has been deprecated then found #597 - should I list the minimum as 0.2.40 rather than 0.2.39 so we can potentially move ahead with #597 sooner?

**Comment by EverlastingBugstopper** [comment]
was this fixed by https://github.com/rustwasm/wasm-pack/commit/97fdc94d535b0f1c3be6aad6424da12267295367? Looks like it was committed directly to master - if so we should close this

**Comment by EverlastingBugstopper** [comment]
@ashleygwilliams this was closed by #684 - we should close this issue
