### ISSUE TITLE
--out-dir should be relative to current directory

### ISSUE THREAD

**Issue by mwillsey** [rustwasm/wasm-pack#704]
## 🐛 Bug description
`wasm-pack build subdir/ --out-dir pkg` dumps the output in `$PWD/subdir/pkg/`.

#### 🤔 Expected Behavior
Should output to `$PWD/pkg`, not the `subdir`. The help says: 

> -d, --out-dir <out_dir>      Sets the output directory with a relative path. [default: pkg]
> --out-name <out_name>    Sets the output file names. Defaults to package name.

My understanding is that "relative" here means relative to the current working directory.

#### 👟 Steps to reproduce
`wasm-pack build subdir/ --out-dir pkg` 

#### 🌍 Your environment
```
$ wasm-pack --version
wasm-pack 0.8.1
```

My use case here is working in a cargo workspace. I like to work in the top-level directory, and keep all of my build artifacts in the top-level `target/` directory. 

Thanks!

**Comment by nalshihabi** [comment]
This seems to result from this line in [`src/command/build.rs`](https://github.com/rustwasm/wasm-pack/blob/52e7539590d692ea6663dcef3f1b2bc45efd00b3/src/command/build.rs#L182).

```Rust
let out_dir = crate_path.join(PathBuf::from(build_opts.out_dir));
```
The `out_dir` path is joined with the crate path. I imagine this can be fixed by just removing the join. I can make the changes if that is wanted.
