### ISSUE TITLE
Version notice missmatch

### ISSUE THREAD

**Issue by extraymond** [rustwasm/wasm-pack#788]
## 🐛 Bug description
wasm-pack stated that I'm not using the latest version(0.9.0) and I'm on a older version(0.9.1), seems like not updating version checking stuff.

Related warn log:

```bash
:-) [WARN]: There's a newer version of wasm-pack available, the new version is: 0.9.0, you are using: 0.9.1. To update, navigate to: https://rustwasm.github.io/wasm-pack/installer/
```

#### 🤔 Expected Behavior
wasm-pack should bless me since I'm always on latest.

#### 👟 Steps to reproduce
wasm-pack cli.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.41.0 stable.

**Comment by ashleygwilliams** [comment]
hi @extraymond - i'm trying to reproduce your issue and i'm having some trouble. we did have a small blip yesterday where we rolled back the 0.9.1 release due to some concerns around chromedriver, but then re-released it. perhaps you ran into this during that time?

are you still able to reproduce this? if so, can you tell me how you have installed wasm-pack (either by npm, cargo, or curl | sh?)

**Comment by extraymond** [comment]
Hi! I've installed again from cargo, and it still calls for update.

Additional note: It's displayed after some action, for example after build. It's not displayed if calling wasm-pack without arguments or --help.

**Comment by extraymond** [comment]
If I installed from npm, the warning is gone. maybe cargo didn't release the newest version?
