### ISSUE TITLE
Please change the way to install wasm-pack

### ISSUE THREAD

**Issue by PonasKovas** [rustwasm/wasm-pack#802]
Piping curl to shell is not a good practice, and is pretty controversial.

https://0x46.net/thoughts/2019/04/27/piping-curl-to-shell/

**Comment by Pauan** [comment]
There are two other alternatives for installation:

1. You can install wasm-pack with npm, which is the ideal way if you have a `package.json` already.

2. You can install wasm-pack with `cargo install wasm-pack`.

These are both listed on the installation page, though you have to click on a link to show them.

However, these two methods are not *inherently* more secure, because npm and cargo packages can both run arbitrary code during installation. And wasm-pack itself can of course run arbitrary code.

So the only truly secure way is to either do a code audit (ideally in a safe sandbox environment), or politely ask your favorite distro to package wasm-pack in their official package repository.
