### ISSUE TITLE
Output npm package index.js does not pass eslint

### ISSUE THREAD

**Issue by carlosouro** [rustwasm/wasm-pack#904]
## 🐛 Bug description
`./pkg/` does not pass eslint `no-unused-vars` rules. 
```bash
/Users/myuser/helloApp/pkg/index.js
  1:13  warning  'wasm' is defined but never used  no-unused-vars
```
Typically this causes only warnings in dev/test builds, but it is disallowed in many production builds.
Not sure if this should be considered a bug or a feature request...

#### 🤔 Expected Behavior
For out of the box interop with most JS build pipelines (eg. create-react-app )`./pkg/` output should comply with eslint default rules with no warnings or errors.

#### 👟 Steps to reproduce
```bash
wasm-pack new test
cd test
wasm-pack build
cd pkg
eslint .
```

**Comment by webmaster128** [comment]
Is this really the expected behaviour? Linter rules change all the time, code styles change all the time and every project used different settings and settings. I think auto-generated code should be ignored by the linter. This can be done by ignoring pkg in the project that includes it, by an `.eslintignore` file in pkg or the header in all the file:

```ts
/* tslint:disable */
/* eslint-disable */
```

This is already happening for the autogenerated .d.ts files.

**Comment by ashleygwilliams** [comment]
I agree with @webmaster128 that I don't think we want to ensure that the generated file necessarily passes all js linters. If you have feedback to improve the generated JS- you can submit a PR to wasm-bindgen.
