### ISSUE TITLE
Package maintenance

### ISSUE THREAD

**Issue by Anuovec** [rustwasm/wasm-pack#914]
Is this still maintained?

**Comment by meck93** [comment]
Good question. I was wondering the same. Maybe one of the maintainers could leave a quick comment about it? 
@ashleygwilliams, @Pauan, @fitzgen or @lucashorward

I really appreciate your work! Thanks!

**Comment by Pauan** [comment]
@ashleygwilliams is the only one who has access to the [wasm-pack crate](https://crates.io/crates/wasm-pack), and she disappeared several months ago, so it's not possible to publish new versions.

And I no longer contribute to Rust. So your best option is to talk to @alexcrichton and try to get the wasm-pack crate reassigned to the Wasm WG, so that way it can be published.

**Comment by meck93** [comment]
Hi @Pauan, thanks a lot for the feedback. It already helps to know! 

@alexcrichton do you have an idea how we should proceed on this topic? Would you like to reassign **wasm-pack** to someone else from the Wasm WG? Or, will **wasm-pack** no longer be maintained?

**Comment by alexcrichton** [comment]
Sorry I don't have the permission to assign the crate on crates.io. I can help move the repository, though. I don't personally have the time to help maintain this though.

**Comment by lucashorward** [comment]
I'm mentioned here, but I'm not a maintainer - only an open-source outside contributor. Sorry I can't help any more.

**Comment by Anuovec** [comment]
@alexcrichton If you can change it, I can maintain the package.

**Comment by alexcrichton** [comment]
As I mentioned, I can only move the repository, not the crates.io crate.

**Comment by ashleygwilliams** [comment]
Clearly, the maintenance of this package needs to be discussed but I don't think it should be transferred to someone random (I mean no personal offense to any volunteers). The Wasm WG is no longer really active, and so there's not a clear group of active and trusted maintainers to hand this off to. I do think a plan should be sorted around longer term maintenance but I'm not personally willing to transfer the package to someone I don't know and I don't think the vetting process should happen on a public GitHub issue. If you'd like to discuss this you can reach out to me at ashley666ashley@gmail.com.

**Comment by pauldorehill** [comment]
In order to move forward from the current stale mate:
- the rust wasm wg seemingly not active
- and the ownership of this key package not under control of rustwasm

I’d suggest to remove it from under the umbrella of rustwasm?

The docs can be updated to show `wasm-pack` as an option and also show how to use `wasm-bindgen-cli` and `wasm-opt` etc. the key point ensuring that the versions match. I think most rust users will quickly get their head around:

```
cargo build --target wasm32-unknown-unknown
wasm-bindgen ./target/wasm32-unknown-unknown/debug/my_app.wasm --target web -no-typescript --out-dir ./dist
```

The current deployment default of using a bundler and wasm-pack gets you very quickly into the weeds of the js ecosystem and its not so explicit as to what is going on: it detracts from the simplicity of using rust tooling.

We could also try some things like adding a build script to `wasm-bindgen` that uses `cargo install --root {}` to add the correct copy of the cli to the out dir: this would simplify other tools that could be built around wasm-bindgen.

**Comment by ashleygwilliams** [comment]
> and the ownership of this key package not under control of rustwasm

^ what do you mean by this?

**Comment by pauldorehill** [comment]
I mean [its not owned by rustwasm](https://crates.io/teams/github:rustwasm:core) and the package is entirely under your stewardship so now the community as a whole can't update and publish it: there are 37 pull requests & the current cargo package version is behind the commits. 

Currently its use is deeply interwoven into how to do rust + wasm: from your comment above you are looking for a maintainer, but are understandably attached to it.

So i'd suggest that we are at a fork in the road: 

- `wasm-pack` is brought into the fold and owned by rustwasm
- It's transferred back to you & we decouple the implied dependence of doing rust + wasm with it

**Comment by ashleygwilliams** [comment]
The issue I am trying to call out is that rustwasm isn't really a thing. I am a member of rustwasm. I have currently no reason to think that transferring the crate to the "rustwasm org" makes any sense. There is no one in the rustwasm org that currently can maintain it (as far as I know). This is why "wasm-pack is brought into the fold and owned by rustwasm" is not an option.

**Comment by ashleygwilliams** [comment]
i am closing this issue and opening a two new ones with the following goals:

1. let's figure out what needs to happen so a next version can be published. there's a lot that needs fixing. one thing holding up PRs is that CI is broken, and should probably be moved to github actions.
2. let's figure out how the maintenance of this project can be handled. i can't do it on my own and i am looking to get a set of people who want to maintain it as a team (one person is not gonna be enough to maintain it).

**Comment by pauldorehill** [comment]
As someone on the outside of [rustwasm](https://rustwasm.github.io/) it looks like a `thing`. But i get it, things fall apart and people have other priorities. 

I'm not sure why closing this issue & replacing with 2 new ones is better: from your answer above it looks like we are at the second fork where it would simply be better to transfer it back to you.

**Comment by ashleygwilliams** [comment]
i replaced with 2 issues because i was hoping i could reduce the urgency of the decision by helping get a new pkg published for ya'll while we figure out what to do.

i am not trying to just like.. stubbornly not publish it. i'm not publishing because it's broken and there's no point in releasing something that won't work. ideally.. we get wasm-pack to a place it can be published so we can just get that done, and in the meantime try to build a team that wants to maintain it.

i understand that the working group looks like a thing. it was for a while. it is not active as a group anymore, but if there were interested people it could be. and i think that'd be a good thing. if you want to just not then.. ok, but like.. let's let other people chime in?

**Comment by Pauan** [comment]
@ashleygwilliams The crate is supposed to be owned by the Core Wasm WG (that is how all the other crates are):

https://crates.io/crates/wasm-bindgen
https://crates.io/crates/js-sys
https://crates.io/crates/web-sys
https://crates.io/crates/gloo

This is done so that maintainers can be reassigned if somebody disappears, because the projects are owned by the Wasm WG as a whole, not individual people. This is standard practice.

You can do that by running the following command:

```sh
cargo owner -a github:rustwasm:core wasm-pack
```

**Comment by ashleygwilliams** [comment]
There is no one on the rustwasm working group that can currently maintain this crate. This does not solve the problem. I am not going to transfer the crate to a defunct set of random people with no organization and plan for its maintenance.

**Comment by ashleygwilliams** [comment]
I am locking this issue. If someone wants to reach out to me please do. If you are a fellow member of the rustwasm working group and want to reach out to me please do.
