### ISSUE TITLE
what needs to happen for the next release of wasm-pack

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#929]
it has been quite a while since wasm-pack has been released. this is an issue to track what needs to be fixed so that we can release a new version of wasm-pack.

**Comment by azriel91** [comment]
Heya, would like for https://github.com/rustwasm/wasm-pack/issues/698 to be fixed in the next release (PR: https://github.com/rustwasm/wasm-pack/pull/851).

**Comment by robojumper** [comment]
It would be great if #886 could be fixed (PR at #887) because the issue broke the game of life example (and basically every rust wasm app derived from it).

**Comment by lucashorward** [comment]
- CI should be functional again, and preferably moved to github actions so that open-source contributors can also see what is happening and fix it / make improvements. I see a lot of the travis ci actions are on pending, but not sure what is wrong (and can't see the details to investigate that either as that requires admin access vs a github action with files inside the repo)
- Old versions of other libs should be updated. In #919, #917  and #926 I see wasm-opt, chromedriver and possibly openssl/curl versions are outdated. In some cases these seem to be responsibly for crashes.

**Comment by lwansbrough** [comment]
#888 can probably ship with trivial changes

**Comment by quaos** [comment]
Deno support?

**Comment by oplik0** [comment]
> Deno support?

#908 addresses this, and it looks like it could be merged with minimal changes - it doesn't change much code and it seems the biggest questionable thing there is creating an empty `.gitignore` file (instead of adding `*` to its contents), so that might be reverted (I think the idea is that deno modules are usually kept online with git and imported from urls, so no reason to make default `.gitignore` ignore the result).

One thing that should be added there is listing `deno` target in `wasm-pack build --help`.

**Comment by torokati44** [comment]
Having a new release with newer `wasm-opt` would indeed be really nice!
(The old `wasm-opt` in the 0.9.1 release has a crash which is the current blocker for https://github.com/ruffle-rs/ruffle/pull/2173. However, at least version 98 seems to work fine.)

**Comment by domoritz** [comment]
https://github.com/rustwasm/wasm-pack/pull/937 would also be awesome so that wasm-pack passes --weak-refs --reference-types through to wasm-bindgen.

For anyone else wondering about a new release, https://github.com/rustwasm/wasm-pack/issues/928 helped clarify the status of this repo for me.

**Comment by tv42** [comment]
This issue seems to one of the two new issues mentioned in https://github.com/rustwasm/wasm-pack/issues/914 without linking. Since #914 is now locked, mention it here so hopefully it'll cross-reference right.

**Comment by serprex** [comment]
#936 is necessary for importing wasm-pack modules in node
